name: Check PR Status

on:
  issue_comment: 
    types: created
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        name: Check for comment
        id: check
        with:
          trigger: '#deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: Checkout
        uses: actions/checkout@v3
        if: steps.check.outputs.triggered == 'true'
        
      - name: Build
        if: steps.check.outputs.triggered == 'true'
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          chmod +x gradlew
          ./gradlew build >~/log.txt
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.3.0
        with:
          message: Build completed!
          filePath: ~/log.txt

        

   
    
       

    
      
