name: Check PR Status

on:
  issue_comment: 
    types: created
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - id: build
      - uses: actions/checkout@v3
        if: steps.check.outputs.triggered == 'true'
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
        if: steps.check.outputs.triggered == 'true'

    # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        if: steps.check.outputs.triggered == 'true'

    # Runs a single command using the runners shell
      - name: Compile and run tests on robot code
        run: ./gradlew build
        if: steps.check.outputs.triggered == 'true'
      
